# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opun < Formula
  desc "AI code agent automation framework"
  homepage "https://github.com/rizome-dev/opun"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.6/opun_Darwin_x86_64.tar.gz"
      sha256 "d924dd181d89ad3c14c4168ab63d3cf11e444f37dc23c184981e13f18caf3522"

      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.6/opun_Darwin_arm64.tar.gz"
      sha256 "fbed3d4b78be2a5dcb0bbcb86719b0f6301f80e596f32776dc62c750346360a6"

      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.6/opun_Linux_x86_64.tar.gz"
      sha256 "7a130bcd33bf53a4fcac4e6fd6cc7b3f6d1ca85b06587d618a7d11e46ac57dfc"
      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.6/opun_Linux_arm64.tar.gz"
      sha256 "30e5264aebd3fcba6915b7badba31a3957fd3ec9f671ee3237c693ae8af198b9"
      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
  end

  test do
    system "#{bin}/opun", "--version"
  end
end
