# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpunNightly < Formula
  desc "AI code agent automation framework (Nightly/Prerelease)"
  homepage "https://github.com/rizome-dev/opun"
  version "0.1.3-nightly"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.3-nightly/opun_Darwin_x86_64.tar.gz"
      sha256 "fed71b41ffb24ea4970537256ec203959934b67d09e01881669d05bf1976320a"

      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.3-nightly/opun_Darwin_arm64.tar.gz"
      sha256 "2cd2c4b0ea1c649c0c15dc8ba258bf588ddb01a18a3a0613c73ff191d6c6fa25"

      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.3-nightly/opun_Linux_x86_64.tar.gz"
      sha256 "a23c3c9f401222f79f7ceb95ca5d594f1c9b560df56590bbb96d5c4c09ad6ea3"
      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.3-nightly/opun_Linux_arm64.tar.gz"
      sha256 "786c268f3861f36cac16c9e16a608feb3bb4bac7153745a0413bafb651f7b18a"
      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
  end

  conflicts_with "opun"

  test do
    system "#{bin}/opun", "--version"
  end
end
