# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opun < Formula
  desc "AI code agent automation framework"
  homepage "https://github.com/rizome-dev/opun"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.3/opun_Darwin_x86_64.tar.gz"
      sha256 "6092c507d17ee68dfbf9eea053578c6004621d2614ccd44be2ebe8e60be43d80"

      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.3/opun_Darwin_arm64.tar.gz"
      sha256 "f20e6a78b2119dbd2f53729b3f8e9e8ad06469d5d7e1c50675f0c365971f9ab9"

      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.3/opun_Linux_x86_64.tar.gz"
      sha256 "04c573dd87d2590dddc7693a2e6082b887f33e9558c226f129b929df8547006e"
      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.3/opun_Linux_arm64.tar.gz"
      sha256 "a7f5efb1ea0f04f7bd8899a7050bdfa0fa8fe1633057c18382f02142bd03b631"
      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
  end

  test do
    system "#{bin}/opun", "--version"
  end
end
