# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opun < Formula
  desc "AI code agent automation framework"
  homepage "https://github.com/rizome-dev/opun"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.0/opun_Darwin_x86_64.tar.gz"
      sha256 "fbd600d743ff8908d3c6b9cc03da4bdd27158378ad39308df88b70c5152bab1e"

      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
    on_arm do
      url "https://github.com/rizome-dev/opun/releases/download/v0.1.0/opun_Darwin_arm64.tar.gz"
      sha256 "52404d663270b0bee275e633a63578e7b9ecfd6d1ea7687da7108fa3334eec8e"

      def install
        bin.install "opun"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"opun", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rizome-dev/opun/releases/download/v0.1.0/opun_Linux_x86_64.tar.gz"
        sha256 "c6d6cc619511cf5c02a22fd02a2bf4702b2d056d6d1e9557fcb4e4f0568c5103"

        def install
          bin.install "opun"

          # Generate and install shell completions
          generate_completions_from_executable(bin/"opun", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rizome-dev/opun/releases/download/v0.1.0/opun_Linux_arm64.tar.gz"
        sha256 "f6dcc1c9958089ccf634b04476b43b543da7c23660879766a2c97cb91dfc46e7"

        def install
          bin.install "opun"

          # Generate and install shell completions
          generate_completions_from_executable(bin/"opun", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/opun", "--version"
  end
end
