# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rizome < Formula
  desc "Agentic development environment workflow management CLI"
  homepage "https://github.com/rizome-dev/rizome"
  version "0.1.0"
  license "GPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rizome-dev/rizome/releases/download/v0.1.0/rizome_Darwin_x86_64.tar.gz"
      sha256 "443b010f3e3297518b72dec46b5939a9bdc28ee1f3bc9ebea3dabbedf596883c"

      def install
        bin.install "rizome"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"rizome", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rizome-dev/rizome/releases/download/v0.1.0/rizome_Darwin_arm64.tar.gz"
      sha256 "16ba4972f5f3ab40bbb723489d915fcee56f2bd3cd39c592172ecdffb208b035"

      def install
        bin.install "rizome"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"rizome", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/rizome-dev/rizome/releases/download/v0.1.0/rizome_Linux_x86_64.tar.gz"
      sha256 "75d6de41b2d8566857605883fe8b2fc0e006c0c67484611f40db36c771f27247"
      def install
        bin.install "rizome"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"rizome", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/rizome-dev/rizome/releases/download/v0.1.0/rizome_Linux_arm64.tar.gz"
      sha256 "30a280f39e858336cdf9ad3f30f1b383cf9056711c5d17ebd80692e6e83893a6"
      def install
        bin.install "rizome"

        # Generate and install shell completions
        generate_completions_from_executable(bin/"rizome", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      ✨ Rizome CLI installation complete!

      Quick Start:
        1. Run 'rizome init' to interactively create a RIZOME.md from templates
        2. Edit RIZOME.md with your project details and provider overrides
        3. Run 'rizome sync' to interactively synchronize provider configurations

      Template Management:
        rizome tmpl        List available templates
        rizome tmpl add    Create a new template interactively
        rizome tmpl edit   Edit an existing template
        rizome tmpl show   Show template content
        rizome tmpl delete Delete a template

      Example RIZOME.md format:
        # RIZOME.md

        Project overview and context.

        ## Common Instructions
        Instructions that apply to all AI providers:
        - Project type and technology stack
        - Coding standards and conventions

        ## Provider Overrides
        ### CLAUDE
        Claude-specific instructions

        ### QWEN
        Qwen-specific instructions

      Commands:
        rizome --help        Show help information
        rizome init          Interactive RIZOME.md creation from templates
        rizome tmpl          Manage RIZOME.md templates
        rizome sync          Interactive provider configuration sync
        rizome sync --dry-run    Preview changes without applying

      For more information: https://github.com/rizome-dev/rizome
    EOS
  end

  test do
    system "#{bin}/rizome", "--help"
    # Test sync command help (should work without RIZOME.md)
    system "#{bin}/rizome", "sync", "--help"
  end
end
